name: Deploy Frontend

on:
  push:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image for Frontend
      run: |
        cd frontend
        docker build -t showboks_frontend .

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: 22
        script: |
          cd /home/showboks/docker/ShowBoks/frontend/
          git pull origin main
          docker-compose down
          docker-compose up -d --build
